CREATE DATABASE IF NOT EXISTS CinemaDB;
USE CinemaDB;

CREATE TABLE IF NOT EXISTS Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(50) NOT NULL,
    Role VARCHAR(20) NOT NULL 
);


INSERT IGNORE INTO Users (Username, Password, Role) VALUES 
('admin', '123', 'admin'),
('gise', '1234', 'user');


CREATE TABLE IF NOT EXISTS Movies (
    MovieID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    Genre VARCHAR(50),
    Duration INT NOT NULL, 
    Director VARCHAR(50),
    PosterPath VARCHAR(500)
);


CREATE TABLE IF NOT EXISTS Halls (
    HallID INT AUTO_INCREMENT PRIMARY KEY,
    HallName VARCHAR(50) NOT NULL,
    Capacity INT DEFAULT 50
);


CREATE TABLE IF NOT EXISTS Sessions (
    SessionID INT AUTO_INCREMENT PRIMARY KEY,
    MovieID INT NOT NULL,
    HallID INT NOT NULL,
    SessionDate DATE NOT NULL,
    SessionTime TIME NOT NULL,
    FOREIGN KEY (MovieID) REFERENCES Movies(MovieID) ON DELETE CASCADE,
    FOREIGN KEY (HallID) REFERENCES Halls(HallID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Tickets (
    TicketID INT AUTO_INCREMENT PRIMARY KEY,
    SessionID INT NOT NULL,
    UserID INT NOT NULL,
    SeatNumber INT NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    PurchaseDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SessionID) REFERENCES Sessions(SessionID) ON DELETE CASCADE,
    FOREIGN KEY (UserID) REFERENCES Users(UserID) ON DELETE CASCADE
);

CREATE TABLE RevenueArchive (
    ArchiveID INT PRIMARY KEY AUTO_INCREMENT,
    OriginalTicketID INT NOT NULL,
    MovieID INT NOT NULL,
    Title VARCHAR(100),
    SessionID_Old INT,
    UserID INT,
    Price DECIMAL(10, 2),
    PurchaseDate DATETIME,
    ArchiveDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MovieID) REFERENCES Movies(MovieID) ON DELETE CASCADE
);

ALTER TABLE tickets 
DROP FOREIGN KEY FK_Tickets_Sessions_Restrict;
ALTER TABLE tickets 
ADD CONSTRAINT FK_Tickets_Sessions_Cascade
FOREIGN KEY (SessionID) REFERENCES sessions(SessionID)
ON DELETE CASCADE;

